### ISSUE TITLE
Encoding problems on some uppercase Turkish chars

### ISSUE THREAD

**Issue by muratcorlu** [emre/PharmacyOnDuty#3]
Screenshot:
<img width="602" alt="screen shot 2016-05-03 at 20 00 59" src="https://cloud.githubusercontent.com/assets/127687/14991486/44811c74-116a-11e6-8867-ca2b55fab887.png">

**Comment by muratcorlu** [comment]
Buradaki metod'da büyük Ş'yi de replace etmek sanki: https://github.com/emre/PharmacyOnDuty/blob/master/pharmacy_on_duty/fetcher.py#L16

Bir de eczene adlarını o fonksiyondan geçirmeyi unutmuş olabilirsin: https://github.com/emre/PharmacyOnDuty/blob/master/pharmacy_on_duty/fetcher.py#L86

Bi pull request iyi giderdi aslında bu kadar yazana kadar :)

**Comment by emre** [comment]
teşekkürler,

https://github.com/emre/PharmacyOnDuty/commit/1789d06d29e96306d13c2184fe22767ba4427390 ile çözülmüş olmalı.

test edebilir misiniz?

/cc @hanakamer

**Comment by hanakamer** [comment]
cozulmus tesekkurler
